services:
  db:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=dbasrm'
      - 'POSTGRES_PASSWORD=admin'
      - 'POSTGRES_USER=admin'
    ports:
      - '5432:5432'

  zookeeper:
    container_name: zookeeper-emprestimo-pagamento
    image: 'confluentinc/cp-zookeeper:latest'
    networks:
      - broker-kafka
    ports:
      - '2181:2181'
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
  kafka:
    container_name: message-emprestimo-pagamento
    image: 'confluentinc/cp-kafka:latest'
    networks:
      - broker-kafka
    depends_on:
      - zookeeper
    ports:
      - 9092:9092
      - 29092:29092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://message:29092,PLAINTEXT_HOST://192.168.0.147:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  kefdrop:
    container_name: kefdrop-emprestimo-pagamento
    image: 'obsidiandynamics/kafdrop:latest'
    networks:
        - broker-kafka
    depends_on:
        - kafka
    ports:
      - '9000:9000'
    environment:
      KAFKA_BROKERCONNECT: message:29092

networks:
    broker-kafka:
        driver: bridge